---
abstract: 'Library for interracting with bash session'
author:
  - huakim
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IPC-Bash
requires:
  Bytes::Random::Secure: '0'
  File::Spec::Functions: '0'
  File::Temp: '0'
  File::Util::Tempdir: '0'
  IPC::Open3: '0'
  Moose: '0'
  MooseX::Privacy: '0'
  Mutex: '0'
  POSIX: '0'
  Symbol: '0'
  perl: '5.006'
  strict: '0'
  threads: '0'
  warnings: '0'
resources:
  homepage: https://github.com/huakim-tyk/IPC-Bash
version: 0.0.1
x_generated_by_perl: v5.36.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
